services:
  app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - /app/node_modules
    stdin_open: true # ✅ Исправлено
    tty: true # ✅ Оставляем для корректной работы в терминале
    environment:
      - CHOKIDAR_USEPOLLING=true
